baseURL = 'https://gabrieldornella.github.io/gabriel-dornella-blog/'
languageCode = 'en-us'
title = 'Gabriel Dornella'

[taxonomies]
  tag = 'tags'
  topic = 'topics'

[params]
  description = 'Notes and learnings about Artificial Intelligence for people building, learning, and navigating the space in practice.'
  author = 'Gabriel Dornella'
  linkedin = 'https://br.linkedin.com/in/gabrieldornella'

[menu]
  [[menu.main]]
    name = 'Home'
    pageRef = '/'
    weight = 10
  [[menu.main]]
    name = 'Posts'
    pageRef = '/posts'
    weight = 20
  [[menu.main]]
    name = 'About'
    pageRef = '/about'
    weight = 30
